spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cookbook?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  sql:
    init:
      mode: never
  liquibase:
    contexts: prod